services:
  nginx:
    build:
      context: nginx/
      dockerfile: Dockerfile
    restart: unless-stopped
    networks:
      webnet: null
      ckannet: null
      kkkggs88408ccsskc8woo8s4: null
      coolify: null
    depends_on:
      ckan:
        condition: service_healthy
    ports:
      - '8001:80'
    container_name: nginx-kkkggs88408ccsskc8woo8s4-030425656098
    
    environment:
      COOLIFY_BRANCH: '"master"'
      COOLIFY_RESOURCE_UUID: kkkggs88408ccsskc8woo8s4
      COOLIFY_CONTAINER_NAME: nginx-kkkggs88408ccsskc8woo8s4-030425656098
      SERVICE_URL_NGINX: 'https://ckan.mataramkota.go.id'
      SERVICE_FQDN_NGINX: ckan.mataramkota.go.id
      COOLIFY_URL: 'https://ckan.mataramkota.go.id'
      COOLIFY_FQDN: ckan.mataramkota.go.id
  ckan:
    build:
      context: ckan/
      dockerfile: Dockerfile
      args:
        - 'TZ=${TZ}'
    networks:
      ckannet: null
      dbnet: null
      solrnet: null
      redisnet: null
      kkkggs88408ccsskc8woo8s4: null
      coolify: null
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
      solr:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - 'ckan-storage:/var/lib/ckan'
      - 'pip-cache:/root/.cache/pip'
      - 'site-packages:/usr/lib/python3.10/site-packages'
    restart: unless-stopped
    healthcheck:
      test:
        - CMD
        - wget
        - '-qO'
        - /dev/null
        - 'http://localhost:5000/api/action/status_show'
      interval: 60s
      timeout: 10s
      retries: 3
    container_name: ckan-kkkggs88408ccsskc8woo8s4-030425660121
    environment:
      TZ: '${TZ}'
      COOLIFY_BRANCH: '"master"'
      COOLIFY_RESOURCE_UUID: kkkggs88408ccsskc8woo8s4
      COOLIFY_CONTAINER_NAME: ckan-kkkggs88408ccsskc8woo8s4-030425660121
      SERVICE_URL_NGINX: 'https://ckan.mataramkota.go.id'
      SERVICE_FQDN_NGINX: ckan.mataramkota.go.id
  datapusher:
    networks:
      ckannet: null
      dbnet: null
      kkkggs88408ccsskc8woo8s4: null
      coolify: null
    image: 'ckan/ckan-base-datapusher:${DATAPUSHER_VERSION}'
    restart: unless-stopped
    healthcheck:
      test:
        - CMD
        - wget
        - '-qO'
        - /dev/null
        - 'http://localhost:8800'
      interval: 60s
      timeout: 10s
      retries: 3
    container_name: datapusher-kkkggs88408ccsskc8woo8s4-030425677807
    environment:
      COOLIFY_BRANCH: '"master"'
      COOLIFY_RESOURCE_UUID: kkkggs88408ccsskc8woo8s4
      COOLIFY_CONTAINER_NAME: datapusher-kkkggs88408ccsskc8woo8s4-030425677807
      SERVICE_URL_NGINX: 'https://ckan.mataramkota.go.id'
      SERVICE_FQDN_NGINX: ckan.mataramkota.go.id
  db:
    build:
      context: postgresql/
    networks:
      dbnet: null
      kkkggs88408ccsskc8woo8s4: null
      coolify: null
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      CKAN_DB_USER: ckandbuser
      CKAN_DB_PASSWORD: ckandbpassword
      CKAN_DB: ckandb
      DATASTORE_READONLY_USER: datastore_ro
      DATASTORE_READONLY_PASSWORD: datastore
      DATASTORE_DB: datastore
      COOLIFY_BRANCH: '"master"'
      COOLIFY_RESOURCE_UUID: kkkggs88408ccsskc8woo8s4
      COOLIFY_CONTAINER_NAME: db-kkkggs88408ccsskc8woo8s4-030425679479
      SERVICE_URL_NGINX: 'https://ckan.mataramkota.go.id'
      SERVICE_FQDN_NGINX: ckan.mataramkota.go.id
    volumes:
      - 'pg-data:/var/lib/postgresql/data'
    restart: unless-stopped
    healthcheck:
      test:
        - CMD
        - pg_isready
        - '-U'
        - '${POSTGRES_USER}'
        - '-d'
        - '${POSTGRES_DB}'
    container_name: db-kkkggs88408ccsskc8woo8s4-030425679479
  solr:
    networks:
      solrnet: null
      kkkggs88408ccsskc8woo8s4: null
      coolify: null
    image: 'ckan/ckan-solr:${SOLR_IMAGE_VERSION}'
    volumes:
      - 'solr-data:/var/solr'
    restart: unless-stopped
    healthcheck:
      test:
        - CMD
        - wget
        - '-qO'
        - /dev/null
        - 'http://localhost:8983/solr/'
    container_name: solr-kkkggs88408ccsskc8woo8s4-030425699770
    environment:
      COOLIFY_BRANCH: '"master"'
      COOLIFY_RESOURCE_UUID: kkkggs88408ccsskc8woo8s4
      COOLIFY_CONTAINER_NAME: solr-kkkggs88408ccsskc8woo8s4-030425699770
      SERVICE_URL_NGINX: 'https://ckan.mataramkota.go.id'
      SERVICE_FQDN_NGINX: ckan.mataramkota.go.id
  redis:
    image: 'redis:${REDIS_VERSION}'
    networks:
      redisnet: null
      kkkggs88408ccsskc8woo8s4: null
      coolify: null
    restart: unless-stopped
    healthcheck:
      test:
        - CMD
        - redis-cli
        - '-e'
        - QUIT
    container_name: redis-kkkggs88408ccsskc8woo8s4-030425704723
    environment:
      COOLIFY_BRANCH: '"master"'
      COOLIFY_RESOURCE_UUID: kkkggs88408ccsskc8woo8s4
      COOLIFY_CONTAINER_NAME: redis-kkkggs88408ccsskc8woo8s4-030425704723
      SERVICE_URL_NGINX: 'https://ckan.mataramkota.go.id'
      SERVICE_FQDN_NGINX: ckan.mataramkota.go.id
volumes:
  ckan-storage:
    name: ckan-storage
  pip-cache:
    name: pip-cache
  site-packages:
    name: site-packages
  pg-data:
    name: pg-data
  solr-data:
    name: solr-data
networks:
  webnet: null
  ckannet: null
  solrnet:
    internal: true
  dbnet:
    internal: true
  redisnet:
    internal: true
  kkkggs88408ccsskc8woo8s4:
    name: kkkggs88408ccsskc8woo8s4
    external: true
  coolify:
    name: coolify
    external: true
configs: {  }
secrets: {  }
